### ISSUE TITLE
flags dont work anymore

### ISSUE THREAD

**Issue by Manubi** [tnovau/react-circle-flags#12]
Hi,
something happened to the github link of the flags as can be seen here:
https://tnovau.github.io/react-circle-flags/gallery

Would be better to add the flags to the package?
cheers

**Comment by tnovau** [comment]
It's related to an issue with the page where the flags are stored

**Comment by Manubi** [comment]
which is github...?

**Comment by tnovau** [comment]
https://github.com/HatScripts/circle-flags/issues/20

**Comment by tnovau** [comment]
Maybe, it will be a good idea to add a feature to use your own CDN
