### ISSUE TITLE
Add the posibility to use your own CDN

### ISSUE THREAD

**Issue by tnovau** [tnovau/react-circle-flags#14]
According to comment in #12 from @Manubi, it will be great to allow the users of the package to use their own CDN to avoid issues.

**Comment by dahmc** [comment]
Why not bundle the flags with the package?

**Comment by tnovau** [comment]
> Why not bundle the flags with the package?

If I do that, I should update this package on every `circle-flags` release.

And also the package will be heavier than now.

**Comment by dahmc** [comment]
But we won't have those issues like now. Also, it still is broken for me after the 0.0.12 release

**Comment by tnovau** [comment]
Solved in 0.0.13
