### ISSUE TITLE
View config getter callback for component 'img' must be a function (received 'undefined'). Make sure to start component names with a capital letter.

### ISSUE THREAD

**Issue by BazingaZeta** [tnovau/react-circle-flags#17]
Hello there,
I am trying to use this package into my React Native repo, so far I am just trying to use the basic example -> 
<CircleFlag countryCode="es" height="35" />

But the terminal is throwing this error preventing me to go further. I am importing the CircleFlag component in this way -> import { CircleFlag } from "react-circle-flags";

I don't know what to do about it. 
Did anyone encounter the same issue?

**Comment by tnovau** [comment]
Hey, how are you?, 


First of all, thanks for using the package!

Second, could you share with me the error you're seeing on the terminal?

**Comment by BazingaZeta** [comment]
Hello there!
So, this is the error.
![Screenshot 2021-08-18 at 09 46 03](https://user-images.githubusercontent.com/40890428/129867662-be970abb-a591-4268-95f5-34f61d9ad0f2.png)

I do not understand why this is thrown, to be honest.

**Comment by tnovau** [comment]
I'll close this issue because this npm package doesn't support react native right now. 

It's a good feature to implement. I'll create a card on the board to keep track of it.
