### ISSUE TITLE
Some flags are not showing anymore

### ISSUE THREAD

**Issue by silvio-e** [tnovau/react-circle-flags#24]
We just noticed that the Spanish flag stopped working today:

https://hatscripts.github.io/circle-flags/flags/es.svg

It seems that this problem exists for some more flags.

**Comment by tnovau** [comment]
Hi, it's related to the most recent commit on:  https://github.com/HatScripts/circle-flags @HatScripts

**Comment by silvio-e** [comment]
Thank you for your quick reaction and the intermediate workaround!

**Comment by tnovau** [comment]
It's working now. Closing this
