### ISSUE TITLE
Some images are not showing

### ISSUE THREAD

**Issue by Zer0NimO-web** [tnovau/react-circle-flags#41]
Hello,
  
   I'm working on a react project which involves circle flags. 
   First of all thank you very much for this great library. 
   
   Problem : some images are not showing while inside a select dropdown, meanwhile it is working outside :
   
<img width="358" alt="circle-flags-issue" src="https://github.com/tnovau/react-circle-flags/assets/54934637/644d9deb-1785-4efb-81d0-7990402f0ea2">

The code is quite simple : 
```tsx
const StyledCircleFlag = styled(CircleFlag)({
  width: '16px',
  height: '16px',
});

// ... stuff

<Menu>
 {countries.map((country: Country, index: number) => (
          <MenuItem key={index} onClick={handleClose}>
            <StyledCircleFlag
              countryCode={country.code}
            />
            <NameContainer>{country.name}</NameContainer>
          </MenuItem>
   ))}
</Menu>
```
I checked country codes but everything looks normal. 

When i look at the DOM i got this : 
```jsx
// Working flag
<img
  data-testid="circle-country-flag"
  aria-label="netherlands Antilles"
  title="netherlands Antilles flag"
  class="css-3o0h5k"
  height="100"
  src="https://hatscripts.github.io/circle-flags/flags/na.svg"
></img>;

// Not working flag
<img
  data-testid="circle-country-flag"
  aria-label="Netherlands Antilles"
  title="Netherlands Antilles flag"
  class="css-3o0h5k"
  height="100"
  src="https://hatscripts.github.io/circle-flags/flags/xx.svg"
></img>;
```

Do you have any idea why src is different ?

**Comment by tnovau** [comment]
Hey, how are you?, first of all, thanks for using the package. Also, thanks for taking the time for reporting this.

I'll fix it now.

**Comment by Zer0NimO-web** [comment]
I just found out, the country code was false inside the dropdown select since it was based on the github circle-flags gallery which is outdated. 
Everything works fine as soon as i use the codes inside countries.js
Thank you for your time.

**Comment by HatScripts** [comment]
> github circle-flags gallery which is outdated.

Hi, owner of the [circle-flags](https://github.com/HatScripts/circle-flags) repo here. What's outdated?

**Comment by Zer0NimO-web** [comment]
Sorry i can't find it anymore but i ended up on a page with a list of 400+ flags with yugoslavia and other flags that are not part of the library.
But your library is working fine in the end... my bad.

**Comment by tnovau** [comment]
Hi @HatScripts, I have to make an update to the library because I have code that validates that the country actually exists and have a flag created, I'll do that soon
