### ISSUE TITLE
Missing languages

### ISSUE THREAD

**Issue by WebDev-Akhil** [tnovau/react-circle-flags#45]
{ code: "jv-ID", name: "Basa Jawa", englishName: "Javanese" },
    { code: "fil", name: "Filipino", englishName: "Filipino" },

**Comment by HatScripts** [comment]
The codes are:
* `jv` for Javanese
* `tl` for Tagalog
* `ceb` for Cebuano

**Comment by WebDev-Akhil** [comment]
Thank you!

What about Filipino language? (`fil`)

<img width="1190" alt="image" src="https://github.com/tnovau/react-circle-flags/assets/25116883/bdc53d13-1922-439a-8750-0097569a891e">

**Comment by HatScripts** [comment]
> What about Filipino language? (`fil`)

I've added `fil` now.

`https://hatscripts.github.io/circle-flags/flags/language/fil.svg`

<img src="https://hatscripts.github.io/circle-flags/flags/language/fil.svg" width="48">
