### ISSUE TITLE
images are not loading in production 

### ISSUE THREAD

**Issue by amirking59** [tnovau/react-circle-flags#48]
![image](https://github.com/user-attachments/assets/2668cd67-9b63-47d0-936d-fe2ac1c39b94)

**Comment by tnovau** [comment]
It's a CDN problem, you're using the default one that's hosted in github, so if you're using it outside of github, you have to host it yourself.

**Comment by tnovau** [comment]
I'm going to work on a way to expose a free CDN

**Comment by tnovau** [comment]
@HatScripts for visibility

**Comment by tnovau** [comment]
Try using: `cdnUrl="https://react-circle-flags.pages.dev/"` and let me know.

It's a new a CDN I hosted for this project

**Comment by tnovau** [comment]
Fixed in version 0.0.22, install new version @amirking59

**Comment by tnovau** [comment]
Just to be sure, how did you fix it in the end? @amirking59
